all: 
	@	gcc -o philo -g -lpthread -D_REENTRANT *.c
flags: 
	@	gcc -o philo -Wall -Wextra -Werror -g -lpthread -D_REENTRANT *.c

visualizer:
	@	gcc -o philo -g -lpthread -D_REENTRANT -D VISUALIZER=1 *.c
